// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: portrait_gen.proto

package echopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PortraitGenService_Generate_FullMethodName = "/echo.portrait.v1.PortraitGenService/Generate"
)

// PortraitGenServiceClient is the client API for PortraitGenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PortraitGenService generates a parametric Portrait deterministically from
// (TraitVector, seed). MVP is server-side parametric rendering using Pillow/Cairo;
// AI image generation is explicitly deferred per docs/05_Technical_Architecture.md.
type PortraitGenServiceClient interface {
	Generate(ctx context.Context, in *GeneratePortraitRequest, opts ...grpc.CallOption) (*GeneratePortraitResponse, error)
}

type portraitGenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortraitGenServiceClient(cc grpc.ClientConnInterface) PortraitGenServiceClient {
	return &portraitGenServiceClient{cc}
}

func (c *portraitGenServiceClient) Generate(ctx context.Context, in *GeneratePortraitRequest, opts ...grpc.CallOption) (*GeneratePortraitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePortraitResponse)
	err := c.cc.Invoke(ctx, PortraitGenService_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortraitGenServiceServer is the server API for PortraitGenService service.
// All implementations must embed UnimplementedPortraitGenServiceServer
// for forward compatibility.
//
// PortraitGenService generates a parametric Portrait deterministically from
// (TraitVector, seed). MVP is server-side parametric rendering using Pillow/Cairo;
// AI image generation is explicitly deferred per docs/05_Technical_Architecture.md.
type PortraitGenServiceServer interface {
	Generate(context.Context, *GeneratePortraitRequest) (*GeneratePortraitResponse, error)
	mustEmbedUnimplementedPortraitGenServiceServer()
}

// UnimplementedPortraitGenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortraitGenServiceServer struct{}

func (UnimplementedPortraitGenServiceServer) Generate(context.Context, *GeneratePortraitRequest) (*GeneratePortraitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedPortraitGenServiceServer) mustEmbedUnimplementedPortraitGenServiceServer() {}
func (UnimplementedPortraitGenServiceServer) testEmbeddedByValue()                            {}

// UnsafePortraitGenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortraitGenServiceServer will
// result in compilation errors.
type UnsafePortraitGenServiceServer interface {
	mustEmbedUnimplementedPortraitGenServiceServer()
}

func RegisterPortraitGenServiceServer(s grpc.ServiceRegistrar, srv PortraitGenServiceServer) {
	// If the following call pancis, it indicates UnimplementedPortraitGenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortraitGenService_ServiceDesc, srv)
}

func _PortraitGenService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePortraitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortraitGenServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortraitGenService_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortraitGenServiceServer).Generate(ctx, req.(*GeneratePortraitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortraitGenService_ServiceDesc is the grpc.ServiceDesc for PortraitGenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortraitGenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.portrait.v1.PortraitGenService",
	HandlerType: (*PortraitGenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _PortraitGenService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portrait_gen.proto",
}
