// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: reflection_gen.proto

package echopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReflectionGenService_Generate_FullMethodName = "/echo.reflection.v1.ReflectionGenService/Generate"
)

// ReflectionGenServiceClient is the client API for ReflectionGenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReflectionGenService runs the two-stage prose-reflection pipeline:
// trait vector + signal moments → template → LLM completion → safety classify
// → tone classify → output. See docs/04_Game_Design.md §"The prose reflection"
// and docs/03_Product_Requirements.md F-LLM-001.
type ReflectionGenServiceClient interface {
	Generate(ctx context.Context, in *GenerateReflectionRequest, opts ...grpc.CallOption) (*GenerateReflectionResponse, error)
}

type reflectionGenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReflectionGenServiceClient(cc grpc.ClientConnInterface) ReflectionGenServiceClient {
	return &reflectionGenServiceClient{cc}
}

func (c *reflectionGenServiceClient) Generate(ctx context.Context, in *GenerateReflectionRequest, opts ...grpc.CallOption) (*GenerateReflectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateReflectionResponse)
	err := c.cc.Invoke(ctx, ReflectionGenService_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReflectionGenServiceServer is the server API for ReflectionGenService service.
// All implementations must embed UnimplementedReflectionGenServiceServer
// for forward compatibility.
//
// ReflectionGenService runs the two-stage prose-reflection pipeline:
// trait vector + signal moments → template → LLM completion → safety classify
// → tone classify → output. See docs/04_Game_Design.md §"The prose reflection"
// and docs/03_Product_Requirements.md F-LLM-001.
type ReflectionGenServiceServer interface {
	Generate(context.Context, *GenerateReflectionRequest) (*GenerateReflectionResponse, error)
	mustEmbedUnimplementedReflectionGenServiceServer()
}

// UnimplementedReflectionGenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReflectionGenServiceServer struct{}

func (UnimplementedReflectionGenServiceServer) Generate(context.Context, *GenerateReflectionRequest) (*GenerateReflectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedReflectionGenServiceServer) mustEmbedUnimplementedReflectionGenServiceServer() {}
func (UnimplementedReflectionGenServiceServer) testEmbeddedByValue()                              {}

// UnsafeReflectionGenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReflectionGenServiceServer will
// result in compilation errors.
type UnsafeReflectionGenServiceServer interface {
	mustEmbedUnimplementedReflectionGenServiceServer()
}

func RegisterReflectionGenServiceServer(s grpc.ServiceRegistrar, srv ReflectionGenServiceServer) {
	// If the following call pancis, it indicates UnimplementedReflectionGenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReflectionGenService_ServiceDesc, srv)
}

func _ReflectionGenService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReflectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReflectionGenServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReflectionGenService_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReflectionGenServiceServer).Generate(ctx, req.(*GenerateReflectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReflectionGenService_ServiceDesc is the grpc.ServiceDesc for ReflectionGenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReflectionGenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.reflection.v1.ReflectionGenService",
	HandlerType: (*ReflectionGenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _ReflectionGenService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reflection_gen.proto",
}
