// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: trait_scoring.proto

package echopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TraitScoringService_Score_FullMethodName = "/echo.trait.v1.TraitScoringService/Score"
)

// TraitScoringServiceClient is the client API for TraitScoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TraitScoringService produces a TraitVector from a finalized playthrough event log.
// See docs/04_Game_Design.md §"Trait model" and docs/05_Technical_Architecture.md
// §"Trait, Portrait, and Reflection pipeline".
//
// The service is intentionally stateless: the caller (core-go) provides
// the finalized event log along with the season id and version so the
// scorer can resolve the trait weights. ml-py never reads core-go's
// Postgres in M1; that coupling lands later behind T-CORE-011-followup.
type TraitScoringServiceClient interface {
	// Score consumes the playthrough's choice events and returns the
	// deterministic Trait Vector. Idempotent on repeated calls with the
	// same input. Auditable: the trait-replay tool (M2) reproduces this
	// output offline.
	Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
}

type traitScoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTraitScoringServiceClient(cc grpc.ClientConnInterface) TraitScoringServiceClient {
	return &traitScoringServiceClient{cc}
}

func (c *traitScoringServiceClient) Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, TraitScoringService_Score_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TraitScoringServiceServer is the server API for TraitScoringService service.
// All implementations must embed UnimplementedTraitScoringServiceServer
// for forward compatibility.
//
// TraitScoringService produces a TraitVector from a finalized playthrough event log.
// See docs/04_Game_Design.md §"Trait model" and docs/05_Technical_Architecture.md
// §"Trait, Portrait, and Reflection pipeline".
//
// The service is intentionally stateless: the caller (core-go) provides
// the finalized event log along with the season id and version so the
// scorer can resolve the trait weights. ml-py never reads core-go's
// Postgres in M1; that coupling lands later behind T-CORE-011-followup.
type TraitScoringServiceServer interface {
	// Score consumes the playthrough's choice events and returns the
	// deterministic Trait Vector. Idempotent on repeated calls with the
	// same input. Auditable: the trait-replay tool (M2) reproduces this
	// output offline.
	Score(context.Context, *ScoreRequest) (*ScoreResponse, error)
	mustEmbedUnimplementedTraitScoringServiceServer()
}

// UnimplementedTraitScoringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTraitScoringServiceServer struct{}

func (UnimplementedTraitScoringServiceServer) Score(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Score not implemented")
}
func (UnimplementedTraitScoringServiceServer) mustEmbedUnimplementedTraitScoringServiceServer() {}
func (UnimplementedTraitScoringServiceServer) testEmbeddedByValue()                             {}

// UnsafeTraitScoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TraitScoringServiceServer will
// result in compilation errors.
type UnsafeTraitScoringServiceServer interface {
	mustEmbedUnimplementedTraitScoringServiceServer()
}

func RegisterTraitScoringServiceServer(s grpc.ServiceRegistrar, srv TraitScoringServiceServer) {
	// If the following call pancis, it indicates UnimplementedTraitScoringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TraitScoringService_ServiceDesc, srv)
}

func _TraitScoringService_Score_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraitScoringServiceServer).Score(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraitScoringService_Score_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraitScoringServiceServer).Score(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TraitScoringService_ServiceDesc is the grpc.ServiceDesc for TraitScoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TraitScoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.trait.v1.TraitScoringService",
	HandlerType: (*TraitScoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Score",
			Handler:    _TraitScoringService_Score_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trait_scoring.proto",
}
