// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v3.12.4
// source: trait_scoring.proto

package echopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One recorded choice on a single vignette. The (vignette_id, choice_id)
// pair indexes into the Season at season_version to find the
// TraitWeight list to aggregate.
type ScoredChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VignetteId    string                 `protobuf:"bytes,1,opt,name=vignette_id,json=vignetteId,proto3" json:"vignette_id,omitempty"`
	ChoiceId      string                 `protobuf:"bytes,2,opt,name=choice_id,json=choiceId,proto3" json:"choice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredChoice) Reset() {
	*x = ScoredChoice{}
	mi := &file_trait_scoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredChoice) ProtoMessage() {}

func (x *ScoredChoice) ProtoReflect() protoreflect.Message {
	mi := &file_trait_scoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredChoice.ProtoReflect.Descriptor instead.
func (*ScoredChoice) Descriptor() ([]byte, []int) {
	return file_trait_scoring_proto_rawDescGZIP(), []int{0}
}

func (x *ScoredChoice) GetVignetteId() string {
	if x != nil {
		return x.VignetteId
	}
	return ""
}

func (x *ScoredChoice) GetChoiceId() string {
	if x != nil {
		return x.ChoiceId
	}
	return ""
}

type ScoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable id of the playthrough being scored. Carried for telemetry /
	// log correlation only; scoring itself doesn't depend on it.
	PlaythroughId string `protobuf:"bytes,1,opt,name=playthrough_id,json=playthroughId,proto3" json:"playthrough_id,omitempty"`
	// The Season the playthrough was played against, at the version that
	// was locked in at playthrough creation. The scorer loads this Season
	// from the content tree to resolve trait weights.
	SeasonId      string `protobuf:"bytes,2,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`
	SeasonVersion int32  `protobuf:"varint,3,opt,name=season_version,json=seasonVersion,proto3" json:"season_version,omitempty"`
	// The finalized choice event log in commit order.
	Events        []*ScoredChoice `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_trait_scoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trait_scoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_trait_scoring_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreRequest) GetPlaythroughId() string {
	if x != nil {
		return x.PlaythroughId
	}
	return ""
}

func (x *ScoreRequest) GetSeasonId() string {
	if x != nil {
		return x.SeasonId
	}
	return ""
}

func (x *ScoreRequest) GetSeasonVersion() int32 {
	if x != nil {
		return x.SeasonVersion
	}
	return 0
}

func (x *ScoreRequest) GetEvents() []*ScoredChoice {
	if x != nil {
		return x.Events
	}
	return nil
}

type ScoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 5-vector: Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism.
	// Values are floats in [-1.0, 1.0]; never displayed clinically to under-18 users.
	BigFive []float64 `protobuf:"fixed64,1,rep,packed,name=big_five,json=bigFive,proto3" json:"big_five,omitempty"`
	// 10-vector mapping to Schwartz Basic Human Values per docs/04_Game_Design.md.
	// Order matches `content.AllDimensions` (SCH-SELF_DIRECTION ... SCH-UNIVERSALISM).
	Schwartz []float64 `protobuf:"fixed64,2,rep,packed,name=schwartz,proto3" json:"schwartz,omitempty"`
	// Three attachment-proxy scores: secure, anxious, avoidant in [0.0, 1.0].
	// Never exposed as labels to under-18 players per docs/08_Data_Privacy_Compliance.md.
	Attachment    []float64 `protobuf:"fixed64,3,rep,packed,name=attachment,proto3" json:"attachment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_trait_scoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trait_scoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_trait_scoring_proto_rawDescGZIP(), []int{2}
}

func (x *ScoreResponse) GetBigFive() []float64 {
	if x != nil {
		return x.BigFive
	}
	return nil
}

func (x *ScoreResponse) GetSchwartz() []float64 {
	if x != nil {
		return x.Schwartz
	}
	return nil
}

func (x *ScoreResponse) GetAttachment() []float64 {
	if x != nil {
		return x.Attachment
	}
	return nil
}

var File_trait_scoring_proto protoreflect.FileDescriptor

var file_trait_scoring_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x72, 0x61, 0x69, 0x74, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x74, 0x72, 0x61, 0x69,
	0x74, 0x2e, 0x76, 0x31, 0x22, 0x4c, 0x0a, 0x0c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x64, 0x43, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x69, 0x67, 0x6e, 0x65,
	0x74, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x22, 0xae, 0x01, 0x0a, 0x0c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x74, 0x68, 0x72, 0x6f, 0x75,
	0x67, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x6c, 0x61,
	0x79, 0x74, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x33,
	0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x64, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x06, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x22, 0x66, 0x0a, 0x0d, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x69, 0x67, 0x5f, 0x66, 0x69, 0x76, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x62, 0x69, 0x67, 0x46, 0x69, 0x76, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x63, 0x68, 0x77, 0x61, 0x72, 0x74, 0x7a, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x08, 0x73, 0x63, 0x68, 0x77, 0x61, 0x72, 0x74, 0x7a, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52,
	0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x59, 0x0a, 0x13, 0x54,
	0x72, 0x61, 0x69, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x42, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x2e, 0x65, 0x63,
	0x68, 0x6f, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x65, 0x63, 0x68, 0x6f, 0x2e,
	0x74, 0x72, 0x61, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x68, 0x6d, 0x65, 0x64, 0x2d, 0x61, 0x62, 0x64, 0x65, 0x6c,
	0x68, 0x61, 0x6c, 0x65, 0x65, 0x6d, 0x2f, 0x65, 0x63, 0x68, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x67, 0x6f, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x65, 0x63, 0x68, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trait_scoring_proto_rawDescOnce sync.Once
	file_trait_scoring_proto_rawDescData = file_trait_scoring_proto_rawDesc
)

func file_trait_scoring_proto_rawDescGZIP() []byte {
	file_trait_scoring_proto_rawDescOnce.Do(func() {
		file_trait_scoring_proto_rawDescData = protoimpl.X.CompressGZIP(file_trait_scoring_proto_rawDescData)
	})
	return file_trait_scoring_proto_rawDescData
}

var file_trait_scoring_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_trait_scoring_proto_goTypes = []any{
	(*ScoredChoice)(nil),  // 0: echo.trait.v1.ScoredChoice
	(*ScoreRequest)(nil),  // 1: echo.trait.v1.ScoreRequest
	(*ScoreResponse)(nil), // 2: echo.trait.v1.ScoreResponse
}
var file_trait_scoring_proto_depIdxs = []int32{
	0, // 0: echo.trait.v1.ScoreRequest.events:type_name -> echo.trait.v1.ScoredChoice
	1, // 1: echo.trait.v1.TraitScoringService.Score:input_type -> echo.trait.v1.ScoreRequest
	2, // 2: echo.trait.v1.TraitScoringService.Score:output_type -> echo.trait.v1.ScoreResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_trait_scoring_proto_init() }
func file_trait_scoring_proto_init() {
	if File_trait_scoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trait_scoring_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trait_scoring_proto_goTypes,
		DependencyIndexes: file_trait_scoring_proto_depIdxs,
		MessageInfos:      file_trait_scoring_proto_msgTypes,
	}.Build()
	File_trait_scoring_proto = out.File
	file_trait_scoring_proto_rawDesc = nil
	file_trait_scoring_proto_goTypes = nil
	file_trait_scoring_proto_depIdxs = nil
}
