# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import asset_gen_pb2 as asset__gen__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in asset_gen_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AssetGenServiceStub(object):
    """AssetGenService — contract for AI 3D asset generation (continuous background).
    See docs/05_Technical_Architecture.md §"Continuous background asset generation"
    and docs/07_AI_Agent_Implementation_Guide.md (T-ML-050/051/052).

    Generation is NEVER inline. Callers declare desired assets; a background worker
    converges the world toward that desired state and marks assets READY once
    generated, optimized, QA-passed, and stored on the CDN. Assets are identified
    by a content-address (stable hash of generation inputs), which makes submission
    idempotent and results cacheable/reproducible.

    Forward contract: the M0 codegen target (`make proto`) builds the three M1
    services; this is wired into codegen when the asset pipeline lands (T-ML-050).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitAsset = channel.unary_unary(
                '/echo.assetgen.v1.AssetGenService/SubmitAsset',
                request_serializer=asset__gen__pb2.SubmitAssetRequest.SerializeToString,
                response_deserializer=asset__gen__pb2.SubmitAssetResponse.FromString,
                _registered_method=True)
        self.GetAssetStatus = channel.unary_unary(
                '/echo.assetgen.v1.AssetGenService/GetAssetStatus',
                request_serializer=asset__gen__pb2.GetAssetStatusRequest.SerializeToString,
                response_deserializer=asset__gen__pb2.Asset.FromString,
                _registered_method=True)
        self.ReconcileManifest = channel.unary_unary(
                '/echo.assetgen.v1.AssetGenService/ReconcileManifest',
                request_serializer=asset__gen__pb2.ReconcileManifestRequest.SerializeToString,
                response_deserializer=asset__gen__pb2.ReconcileManifestResponse.FromString,
                _registered_method=True)
        self.ListAssets = channel.unary_unary(
                '/echo.assetgen.v1.AssetGenService/ListAssets',
                request_serializer=asset__gen__pb2.ListAssetsRequest.SerializeToString,
                response_deserializer=asset__gen__pb2.ListAssetsResponse.FromString,
                _registered_method=True)


class AssetGenServiceServicer(object):
    """AssetGenService — contract for AI 3D asset generation (continuous background).
    See docs/05_Technical_Architecture.md §"Continuous background asset generation"
    and docs/07_AI_Agent_Implementation_Guide.md (T-ML-050/051/052).

    Generation is NEVER inline. Callers declare desired assets; a background worker
    converges the world toward that desired state and marks assets READY once
    generated, optimized, QA-passed, and stored on the CDN. Assets are identified
    by a content-address (stable hash of generation inputs), which makes submission
    idempotent and results cacheable/reproducible.

    Forward contract: the M0 codegen target (`make proto`) builds the three M1
    services; this is wired into codegen when the asset pipeline lands (T-ML-050).
    """

    def SubmitAsset(self, request, context):
        """Declare/enqueue a single asset. Idempotent on content-address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssetStatus(self, request, context):
        """Poll a single asset by content-address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconcileManifest(self, request, context):
        """Diff desired vs ready for a Season and enqueue the difference — the
        continuous-reconciliation entry point. Honours budget_cap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAssets(self, request, context):
        """List assets for a Season, optionally filtered by status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssetGenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAsset,
                    request_deserializer=asset__gen__pb2.SubmitAssetRequest.FromString,
                    response_serializer=asset__gen__pb2.SubmitAssetResponse.SerializeToString,
            ),
            'GetAssetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssetStatus,
                    request_deserializer=asset__gen__pb2.GetAssetStatusRequest.FromString,
                    response_serializer=asset__gen__pb2.Asset.SerializeToString,
            ),
            'ReconcileManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconcileManifest,
                    request_deserializer=asset__gen__pb2.ReconcileManifestRequest.FromString,
                    response_serializer=asset__gen__pb2.ReconcileManifestResponse.SerializeToString,
            ),
            'ListAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAssets,
                    request_deserializer=asset__gen__pb2.ListAssetsRequest.FromString,
                    response_serializer=asset__gen__pb2.ListAssetsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echo.assetgen.v1.AssetGenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('echo.assetgen.v1.AssetGenService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssetGenService(object):
    """AssetGenService — contract for AI 3D asset generation (continuous background).
    See docs/05_Technical_Architecture.md §"Continuous background asset generation"
    and docs/07_AI_Agent_Implementation_Guide.md (T-ML-050/051/052).

    Generation is NEVER inline. Callers declare desired assets; a background worker
    converges the world toward that desired state and marks assets READY once
    generated, optimized, QA-passed, and stored on the CDN. Assets are identified
    by a content-address (stable hash of generation inputs), which makes submission
    idempotent and results cacheable/reproducible.

    Forward contract: the M0 codegen target (`make proto`) builds the three M1
    services; this is wired into codegen when the asset pipeline lands (T-ML-050).
    """

    @staticmethod
    def SubmitAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.assetgen.v1.AssetGenService/SubmitAsset',
            asset__gen__pb2.SubmitAssetRequest.SerializeToString,
            asset__gen__pb2.SubmitAssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.assetgen.v1.AssetGenService/GetAssetStatus',
            asset__gen__pb2.GetAssetStatusRequest.SerializeToString,
            asset__gen__pb2.Asset.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconcileManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.assetgen.v1.AssetGenService/ReconcileManifest',
            asset__gen__pb2.ReconcileManifestRequest.SerializeToString,
            asset__gen__pb2.ReconcileManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.assetgen.v1.AssetGenService/ListAssets',
            asset__gen__pb2.ListAssetsRequest.SerializeToString,
            asset__gen__pb2.ListAssetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
