# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import reflection_gen_pb2 as reflection__gen__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reflection_gen_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReflectionGenServiceStub(object):
    """ReflectionGenService runs the two-stage prose-reflection pipeline:
    trait vector + signal moments → template → LLM completion → safety classify
    → tone classify → output. See docs/04_Game_Design.md §"The prose reflection"
    and docs/03_Product_Requirements.md F-LLM-001.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/echo.reflection.v1.ReflectionGenService/Generate',
                request_serializer=reflection__gen__pb2.GenerateReflectionRequest.SerializeToString,
                response_deserializer=reflection__gen__pb2.GenerateReflectionResponse.FromString,
                _registered_method=True)


class ReflectionGenServiceServicer(object):
    """ReflectionGenService runs the two-stage prose-reflection pipeline:
    trait vector + signal moments → template → LLM completion → safety classify
    → tone classify → output. See docs/04_Game_Design.md §"The prose reflection"
    and docs/03_Product_Requirements.md F-LLM-001.
    """

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReflectionGenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=reflection__gen__pb2.GenerateReflectionRequest.FromString,
                    response_serializer=reflection__gen__pb2.GenerateReflectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echo.reflection.v1.ReflectionGenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('echo.reflection.v1.ReflectionGenService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReflectionGenService(object):
    """ReflectionGenService runs the two-stage prose-reflection pipeline:
    trait vector + signal moments → template → LLM completion → safety classify
    → tone classify → output. See docs/04_Game_Design.md §"The prose reflection"
    and docs/03_Product_Requirements.md F-LLM-001.
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo.reflection.v1.ReflectionGenService/Generate',
            reflection__gen__pb2.GenerateReflectionRequest.SerializeToString,
            reflection__gen__pb2.GenerateReflectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
