# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reflection_gen.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reflection_gen.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14reflection_gen.proto\x12\x12\x65\x63ho.reflection.v1\"\xa7\x01\n\x19GenerateReflectionRequest\x12\x16\n\x0eplaythrough_id\x18\x01 \x01(\t\x12\x12\n\nyouth_safe\x18\x02 \x01(\x08\x12\x0e\n\x06locale\x18\x03 \x01(\t\x12\x10\n\x08\x62ig_five\x18\x04 \x03(\x01\x12\x10\n\x08schwartz\x18\x05 \x03(\x01\x12\x12\n\nattachment\x18\x06 \x03(\x01\x12\x16\n\x0esignal_moments\x18\x07 \x03(\t\"V\n\x1aGenerateReflectionResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x15\n\rused_fallback\x18\x02 \x01(\x08\x12\x13\n\x0btemplate_id\x18\x03 \x01(\t2\x81\x01\n\x14ReflectionGenService\x12i\n\x08Generate\x12-.echo.reflection.v1.GenerateReflectionRequest\x1a..echo.reflection.v1.GenerateReflectionResponseB@Z>github.com/ahmed-abdelhaleem/echo/services/core-go/grpc/echopbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reflection_gen_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/ahmed-abdelhaleem/echo/services/core-go/grpc/echopb'
  _globals['_GENERATEREFLECTIONREQUEST']._serialized_start=45
  _globals['_GENERATEREFLECTIONREQUEST']._serialized_end=212
  _globals['_GENERATEREFLECTIONRESPONSE']._serialized_start=214
  _globals['_GENERATEREFLECTIONRESPONSE']._serialized_end=300
  _globals['_REFLECTIONGENSERVICE']._serialized_start=303
  _globals['_REFLECTIONGENSERVICE']._serialized_end=432
# @@protoc_insertion_point(module_scope)
