# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trait_scoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trait_scoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13trait_scoring.proto\x12\recho.trait.v1\"6\n\x0cScoredChoice\x12\x13\n\x0bvignette_id\x18\x01 \x01(\t\x12\x11\n\tchoice_id\x18\x02 \x01(\t\"~\n\x0cScoreRequest\x12\x16\n\x0eplaythrough_id\x18\x01 \x01(\t\x12\x11\n\tseason_id\x18\x02 \x01(\t\x12\x16\n\x0eseason_version\x18\x03 \x01(\x05\x12+\n\x06\x65vents\x18\x04 \x03(\x0b\x32\x1b.echo.trait.v1.ScoredChoice\"G\n\rScoreResponse\x12\x10\n\x08\x62ig_five\x18\x01 \x03(\x01\x12\x10\n\x08schwartz\x18\x02 \x03(\x01\x12\x12\n\nattachment\x18\x03 \x03(\x01\x32Y\n\x13TraitScoringService\x12\x42\n\x05Score\x12\x1b.echo.trait.v1.ScoreRequest\x1a\x1c.echo.trait.v1.ScoreResponseB@Z>github.com/ahmed-abdelhaleem/echo/services/core-go/grpc/echopbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trait_scoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/ahmed-abdelhaleem/echo/services/core-go/grpc/echopb'
  _globals['_SCOREDCHOICE']._serialized_start=38
  _globals['_SCOREDCHOICE']._serialized_end=92
  _globals['_SCOREREQUEST']._serialized_start=94
  _globals['_SCOREREQUEST']._serialized_end=220
  _globals['_SCORERESPONSE']._serialized_start=222
  _globals['_SCORERESPONSE']._serialized_end=293
  _globals['_TRAITSCORINGSERVICE']._serialized_start=295
  _globals['_TRAITSCORINGSERVICE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
